-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 12:03:25 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cinema_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinema_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema_project` DEFAULT CHARACTER SET utf8 ;
USE `cinema_project` ;

-- -----------------------------------------------------
-- Table `cinema_project`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`user_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`tarjet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`tarjet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `money` DECIMAL(10,2) NULL,
  `expiry` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `age` INT NULL,
  `email` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `phone` INT NULL,
  `user_type_id` INT NOT NULL,
  `tarjet_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_type_idx` (`user_type_id` ASC),
  INDEX `fk_user_tarjet1_idx` (`tarjet_id` ASC),
  CONSTRAINT `fk_user_user_type`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `cinema_project`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_tarjet1`
    FOREIGN KEY (`tarjet_id`)
    REFERENCES `cinema_project`.`tarjet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`bar_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`bar_ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateTicket` DATE NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bar_ticket_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_bar_ticket_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema_project`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`film_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`film_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`film` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `releaseDate` DATE NULL,
  `room_id` INT NOT NULL,
  `film_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_film_room1_idx` (`room_id` ASC),
  INDEX `fk_film_film_type1_idx` (`film_type_id` ASC),
  CONSTRAINT `fk_film_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `cinema_project`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_film_type1`
    FOREIGN KEY (`film_type_id`)
    REFERENCES `cinema_project`.`film_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`film_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`film_ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateTicket` DATE NULL,
  `user_id` INT NOT NULL,
  `film_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_film_ticket_user1_idx` (`user_id` ASC),
  INDEX `fk_film_ticket_film1_idx` (`film_id` ASC),
  CONSTRAINT `fk_film_ticket_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema_project`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_ticket_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `cinema_project`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timeSchedule` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`chair_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`chair_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`chair`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`chair` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `film_ticket_id` INT NOT NULL,
  `chair_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chair_film_ticket1_idx` (`film_ticket_id` ASC),
  INDEX `fk_chair_chair_type1_idx` (`chair_type_id` ASC),
  CONSTRAINT `fk_chair_film_ticket1`
    FOREIGN KEY (`film_ticket_id`)
    REFERENCES `cinema_project`.`film_ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chair_chair_type1`
    FOREIGN KEY (`chair_type_id`)
    REFERENCES `cinema_project`.`chair_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`director` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`actor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`product_has_bar_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`product_has_bar_ticket` (
  `product_id` INT NOT NULL,
  `bar_ticket_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `bar_ticket_id`),
  INDEX `fk_product_has_bar_ticket_bar_ticket1_idx` (`bar_ticket_id` ASC),
  INDEX `fk_product_has_bar_ticket_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_bar_ticket_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `cinema_project`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_bar_ticket_bar_ticket1`
    FOREIGN KEY (`bar_ticket_id`)
    REFERENCES `cinema_project`.`bar_ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`film_ticket_has_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`film_ticket_has_schedule` (
  `film_ticket_id` INT NOT NULL,
  `schedule_id` INT NOT NULL,
  PRIMARY KEY (`film_ticket_id`, `schedule_id`),
  INDEX `fk_film_ticket_has_schedule_schedule1_idx` (`schedule_id` ASC),
  INDEX `fk_film_ticket_has_schedule_film_ticket1_idx` (`film_ticket_id` ASC),
  CONSTRAINT `fk_film_ticket_has_schedule_film_ticket1`
    FOREIGN KEY (`film_ticket_id`)
    REFERENCES `cinema_project`.`film_ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_ticket_has_schedule_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `cinema_project`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`film_has_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`film_has_genre` (
  `film_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`film_id`, `genre_id`),
  INDEX `fk_film_has_genre_genre1_idx` (`genre_id` ASC),
  INDEX `fk_film_has_genre_film1_idx` (`film_id` ASC),
  CONSTRAINT `fk_film_has_genre_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `cinema_project`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_has_genre_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `cinema_project`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`film_has_director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`film_has_director` (
  `film_id` INT NOT NULL,
  `director_id` INT NOT NULL,
  PRIMARY KEY (`film_id`, `director_id`),
  INDEX `fk_film_has_director_director1_idx` (`director_id` ASC),
  INDEX `fk_film_has_director_film1_idx` (`film_id` ASC),
  CONSTRAINT `fk_film_has_director_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `cinema_project`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_has_director_director1`
    FOREIGN KEY (`director_id`)
    REFERENCES `cinema_project`.`director` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema_project`.`film_has_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_project`.`film_has_actor` (
  `film_id` INT NOT NULL,
  `actor_id` INT NOT NULL,
  PRIMARY KEY (`film_id`, `actor_id`),
  INDEX `fk_film_has_actor_actor1_idx` (`actor_id` ASC),
  INDEX `fk_film_has_actor_film1_idx` (`film_id` ASC),
  CONSTRAINT `fk_film_has_actor_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `cinema_project`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_has_actor_actor1`
    FOREIGN KEY (`actor_id`)
    REFERENCES `cinema_project`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
